// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var SplayApi = SplayApi || {};

/**
 * @enum {number}
 */
SplayApi.UNIVERSE_TYPE = {
  DMX: 0,
  ARTNET: 1,
  SACN: 2,
  NONE: 3
};

/**
 * @enum {string}
 */
SplayApi.UNIVERSE_TYPEName = {
  '0': 'DMX',
  '1': 'ARTNET',
  '2': 'SACN',
  '3': 'NONE'
};

/**
 * Don't change order
 *
 * @enum {number}
 */
SplayApi.PIXEL_ORDER = {
  RGB: 0,
  RBG: 1,
  GRB: 2,
  GBR: 3,
  BRG: 4,
  BGR: 5,
  RGBW: 6,
  RBGW: 7,
  GRBW: 8,
  GBRW: 9,
  BRGW: 10,
  BGRW: 11,
  WRGB: 12,
  WRBG: 13,
  WGRB: 14,
  WGBR: 15,
  WBRG: 16,
  WBGR: 17,
  RWGB: 18,
  RWBG: 19,
  GWRB: 20,
  GWBR: 21,
  BWRG: 22,
  BWGR: 23,
  RGWB: 24,
  RBWG: 25,
  GRWB: 26,
  GBWR: 27,
  BRWG: 28,
  BGWR: 29,
  W: 30
};

/**
 * Don't change order
 *
 * @enum {string}
 */
SplayApi.PIXEL_ORDERName = {
  '0': 'RGB',
  '1': 'RBG',
  '2': 'GRB',
  '3': 'GBR',
  '4': 'BRG',
  '5': 'BGR',
  '6': 'RGBW',
  '7': 'RBGW',
  '8': 'GRBW',
  '9': 'GBRW',
  '10': 'BRGW',
  '11': 'BGRW',
  '12': 'WRGB',
  '13': 'WRBG',
  '14': 'WGRB',
  '15': 'WGBR',
  '16': 'WBRG',
  '17': 'WBGR',
  '18': 'RWGB',
  '19': 'RWBG',
  '20': 'GWRB',
  '21': 'GWBR',
  '22': 'BWRG',
  '23': 'BWGR',
  '24': 'RGWB',
  '25': 'RBWG',
  '26': 'GRWB',
  '27': 'GBWR',
  '28': 'BRWG',
  '29': 'BGWR',
  '30': 'W'
};

/**
 * @enum {number}
 */
SplayApi.SETTING_CATEGORIES = {
  IS_SPARE: 0,
  SYSTEM_NAME: 1,
  PLAYBACK_CONFIG: 2,
  PASSWORD: 3,
  HELP_HINTS: 4,
  SERIALNO: 5,
  ENABLE_PASSWORD: 6,
  SMTP: 7,
  EMAIL: 8,
  INPUT: 9,
  OUTPUT: 10,
  DMX: 11,
  ARTNET: 12,
  SACN: 13,
  LOCATION: 14,
  NTP: 15,
  BASE_PATH: 16,
  CUE_PATH: 17,
  HOME_INTERFACE: 18,
  UDP: 19,
  TCP: 20,
  RS232C: 21,
  OSC: 22,
  IEEE1588_CONFIG: 23,
  IEEE1588_ACTIVE: 24,
  LOCK_STATUS: 25,
  DB_VERSION: 26,
  SIZE_OF: 27
};

/**
 * @enum {string}
 */
SplayApi.SETTING_CATEGORIESName = {
  '0': 'IS_SPARE',
  '1': 'SYSTEM_NAME',
  '2': 'PLAYBACK_CONFIG',
  '3': 'PASSWORD',
  '4': 'HELP_HINTS',
  '5': 'SERIALNO',
  '6': 'ENABLE_PASSWORD',
  '7': 'SMTP',
  '8': 'EMAIL',
  '9': 'INPUT',
  '10': 'OUTPUT',
  '11': 'DMX',
  '12': 'ARTNET',
  '13': 'SACN',
  '14': 'LOCATION',
  '15': 'NTP',
  '16': 'BASE_PATH',
  '17': 'CUE_PATH',
  '18': 'HOME_INTERFACE',
  '19': 'UDP',
  '20': 'TCP',
  '21': 'RS232C',
  '22': 'OSC',
  '23': 'IEEE1588_CONFIG',
  '24': 'IEEE1588_ACTIVE',
  '25': 'LOCK_STATUS',
  '26': 'DB_VERSION',
  '27': 'SIZE_OF'
};

// Exports for ECMAScript6 Modules
export {SplayApi};
