#!/bin/sh

if [ -e .commit ]
then
    rm .commit
    # Run Flatbuffer compiler (linux built version put into repo) for cpp and js
    .githooks/flatc --cpp -o cpp fbs/*.fbs
    .githooks/flatc --js --es6-js-export -o js fbs/*.fbs
    # Add generated to commit
    git add cpp/* js/*
    git commit --amend -C HEAD --no-verify
fi