#!/bin/sh

if [ -e .commit ]
then
    rm .commit
    # Run Flatbuffer compiler for cpp and js & Add generated to commit
    flatc --cpp -o cpp fbs/*.fbs
    flatc --js --es6-js-export -o js fbs/*.fbs
    git add cpp/* js/*
    git commit --amend -C HEAD --no-verify
fi