// automatically generated by the FlatBuffers compiler, do not modify

import { BackupInfo } from '../splay-api/backup-info.js';
import { DiscoveryInfo } from '../splay-api/discovery-info.js';
import { DmxFrame } from '../splay-api/dmx-frame.js';
import { GetAllCuesReq } from '../splay-api/get-all-cues-req.js';
import { GetAllCuesRes } from '../splay-api/get-all-cues-res.js';
import { GetAllPlaylistsReq } from '../splay-api/get-all-playlists-req.js';
import { GetAllPlaylistsRes } from '../splay-api/get-all-playlists-res.js';
import { GetCueReq } from '../splay-api/get-cue-req.js';
import { GetCueRes } from '../splay-api/get-cue-res.js';
import { GetPlaylistReq } from '../splay-api/get-playlist-req.js';
import { GetPlaylistRes } from '../splay-api/get-playlist-res.js';
import { GetUploadStatus } from '../splay-api/get-upload-status.js';
import { PausePlaylistReq } from '../splay-api/pause-playlist-req.js';
import { PlayPlaylistReq } from '../splay-api/play-playlist-req.js';
import { PlayingCuesList } from '../splay-api/playing-cues-list.js';
import { RecordStop } from '../splay-api/record-stop.js';
import { RestorePackage } from '../splay-api/restore-package.js';
import { StatusRes } from '../splay-api/status-res.js';
import { StopPlaylistReq } from '../splay-api/stop-playlist-req.js';
import { SystemInfo } from '../splay-api/system-info.js';


export enum Body {
  NONE = 0,
  StatusRes = 1,
  PlayPlaylistReq = 2,
  PausePlaylistReq = 3,
  StopPlaylistReq = 4,
  GetPlaylistReq = 5,
  GetPlaylistRes = 6,
  GetAllPlaylistsReq = 7,
  GetAllPlaylistsRes = 8,
  GetCueReq = 9,
  GetCueRes = 10,
  GetAllCuesReq = 11,
  GetAllCuesRes = 12,
  GetUploadStatus = 13,
  SystemInfo = 14,
  RestorePackage = 15,
  BackupInfo = 16,
  DiscoveryInfo = 17,
  DmxFrame = 18,
  RecordStop = 19,
  PlayingCuesList = 20
}

export function unionToBody(
  type: Body,
  accessor: (obj:BackupInfo|DiscoveryInfo|DmxFrame|GetAllCuesReq|GetAllCuesRes|GetAllPlaylistsReq|GetAllPlaylistsRes|GetCueReq|GetCueRes|GetPlaylistReq|GetPlaylistRes|GetUploadStatus|PausePlaylistReq|PlayPlaylistReq|PlayingCuesList|RecordStop|RestorePackage|StatusRes|StopPlaylistReq|SystemInfo) => BackupInfo|DiscoveryInfo|DmxFrame|GetAllCuesReq|GetAllCuesRes|GetAllPlaylistsReq|GetAllPlaylistsRes|GetCueReq|GetCueRes|GetPlaylistReq|GetPlaylistRes|GetUploadStatus|PausePlaylistReq|PlayPlaylistReq|PlayingCuesList|RecordStop|RestorePackage|StatusRes|StopPlaylistReq|SystemInfo|null
): BackupInfo|DiscoveryInfo|DmxFrame|GetAllCuesReq|GetAllCuesRes|GetAllPlaylistsReq|GetAllPlaylistsRes|GetCueReq|GetCueRes|GetPlaylistReq|GetPlaylistRes|GetUploadStatus|PausePlaylistReq|PlayPlaylistReq|PlayingCuesList|RecordStop|RestorePackage|StatusRes|StopPlaylistReq|SystemInfo|null {
  switch(Body[type]) {
    case 'NONE': return null; 
    case 'StatusRes': return accessor(new StatusRes())! as StatusRes;
    case 'PlayPlaylistReq': return accessor(new PlayPlaylistReq())! as PlayPlaylistReq;
    case 'PausePlaylistReq': return accessor(new PausePlaylistReq())! as PausePlaylistReq;
    case 'StopPlaylistReq': return accessor(new StopPlaylistReq())! as StopPlaylistReq;
    case 'GetPlaylistReq': return accessor(new GetPlaylistReq())! as GetPlaylistReq;
    case 'GetPlaylistRes': return accessor(new GetPlaylistRes())! as GetPlaylistRes;
    case 'GetAllPlaylistsReq': return accessor(new GetAllPlaylistsReq())! as GetAllPlaylistsReq;
    case 'GetAllPlaylistsRes': return accessor(new GetAllPlaylistsRes())! as GetAllPlaylistsRes;
    case 'GetCueReq': return accessor(new GetCueReq())! as GetCueReq;
    case 'GetCueRes': return accessor(new GetCueRes())! as GetCueRes;
    case 'GetAllCuesReq': return accessor(new GetAllCuesReq())! as GetAllCuesReq;
    case 'GetAllCuesRes': return accessor(new GetAllCuesRes())! as GetAllCuesRes;
    case 'GetUploadStatus': return accessor(new GetUploadStatus())! as GetUploadStatus;
    case 'SystemInfo': return accessor(new SystemInfo())! as SystemInfo;
    case 'RestorePackage': return accessor(new RestorePackage())! as RestorePackage;
    case 'BackupInfo': return accessor(new BackupInfo())! as BackupInfo;
    case 'DiscoveryInfo': return accessor(new DiscoveryInfo())! as DiscoveryInfo;
    case 'DmxFrame': return accessor(new DmxFrame())! as DmxFrame;
    case 'RecordStop': return accessor(new RecordStop())! as RecordStop;
    case 'PlayingCuesList': return accessor(new PlayingCuesList())! as PlayingCuesList;
    default: return null;
  }
}

export function unionListToBody(
  type: Body, 
  accessor: (index: number, obj:BackupInfo|DiscoveryInfo|DmxFrame|GetAllCuesReq|GetAllCuesRes|GetAllPlaylistsReq|GetAllPlaylistsRes|GetCueReq|GetCueRes|GetPlaylistReq|GetPlaylistRes|GetUploadStatus|PausePlaylistReq|PlayPlaylistReq|PlayingCuesList|RecordStop|RestorePackage|StatusRes|StopPlaylistReq|SystemInfo) => BackupInfo|DiscoveryInfo|DmxFrame|GetAllCuesReq|GetAllCuesRes|GetAllPlaylistsReq|GetAllPlaylistsRes|GetCueReq|GetCueRes|GetPlaylistReq|GetPlaylistRes|GetUploadStatus|PausePlaylistReq|PlayPlaylistReq|PlayingCuesList|RecordStop|RestorePackage|StatusRes|StopPlaylistReq|SystemInfo|null, 
  index: number
): BackupInfo|DiscoveryInfo|DmxFrame|GetAllCuesReq|GetAllCuesRes|GetAllPlaylistsReq|GetAllPlaylistsRes|GetCueReq|GetCueRes|GetPlaylistReq|GetPlaylistRes|GetUploadStatus|PausePlaylistReq|PlayPlaylistReq|PlayingCuesList|RecordStop|RestorePackage|StatusRes|StopPlaylistReq|SystemInfo|null {
  switch(Body[type]) {
    case 'NONE': return null; 
    case 'StatusRes': return accessor(index, new StatusRes())! as StatusRes;
    case 'PlayPlaylistReq': return accessor(index, new PlayPlaylistReq())! as PlayPlaylistReq;
    case 'PausePlaylistReq': return accessor(index, new PausePlaylistReq())! as PausePlaylistReq;
    case 'StopPlaylistReq': return accessor(index, new StopPlaylistReq())! as StopPlaylistReq;
    case 'GetPlaylistReq': return accessor(index, new GetPlaylistReq())! as GetPlaylistReq;
    case 'GetPlaylistRes': return accessor(index, new GetPlaylistRes())! as GetPlaylistRes;
    case 'GetAllPlaylistsReq': return accessor(index, new GetAllPlaylistsReq())! as GetAllPlaylistsReq;
    case 'GetAllPlaylistsRes': return accessor(index, new GetAllPlaylistsRes())! as GetAllPlaylistsRes;
    case 'GetCueReq': return accessor(index, new GetCueReq())! as GetCueReq;
    case 'GetCueRes': return accessor(index, new GetCueRes())! as GetCueRes;
    case 'GetAllCuesReq': return accessor(index, new GetAllCuesReq())! as GetAllCuesReq;
    case 'GetAllCuesRes': return accessor(index, new GetAllCuesRes())! as GetAllCuesRes;
    case 'GetUploadStatus': return accessor(index, new GetUploadStatus())! as GetUploadStatus;
    case 'SystemInfo': return accessor(index, new SystemInfo())! as SystemInfo;
    case 'RestorePackage': return accessor(index, new RestorePackage())! as RestorePackage;
    case 'BackupInfo': return accessor(index, new BackupInfo())! as BackupInfo;
    case 'DiscoveryInfo': return accessor(index, new DiscoveryInfo())! as DiscoveryInfo;
    case 'DmxFrame': return accessor(index, new DmxFrame())! as DmxFrame;
    case 'RecordStop': return accessor(index, new RecordStop())! as RecordStop;
    case 'PlayingCuesList': return accessor(index, new PlayingCuesList())! as PlayingCuesList;
    default: return null;
  }
}
