// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { COMMAND } from '../splay-api/command.js';


export class GetPlaylistReq {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetPlaylistReq {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetPlaylistReq(bb:flatbuffers.ByteBuffer, obj?:GetPlaylistReq):GetPlaylistReq {
  return (obj || new GetPlaylistReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetPlaylistReq(bb:flatbuffers.ByteBuffer, obj?:GetPlaylistReq):GetPlaylistReq {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetPlaylistReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

command():COMMAND {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : COMMAND.GET_PLAYLIST;
}

playlistId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startGetPlaylistReq(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCommand(builder:flatbuffers.Builder, command:COMMAND) {
  builder.addFieldInt8(0, command, COMMAND.GET_PLAYLIST);
}

static addPlaylistId(builder:flatbuffers.Builder, playlistId:number) {
  builder.addFieldInt32(1, playlistId, 0);
}

static endGetPlaylistReq(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetPlaylistReq(builder:flatbuffers.Builder, command:COMMAND, playlistId:number):flatbuffers.Offset {
  GetPlaylistReq.startGetPlaylistReq(builder);
  GetPlaylistReq.addCommand(builder, command);
  GetPlaylistReq.addPlaylistId(builder, playlistId);
  return GetPlaylistReq.endGetPlaylistReq(builder);
}
}
