// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { COMMAND } from '../splay-api/command.js';


export class GetAllPlaylistsReq {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetAllPlaylistsReq {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetAllPlaylistsReq(bb:flatbuffers.ByteBuffer, obj?:GetAllPlaylistsReq):GetAllPlaylistsReq {
  return (obj || new GetAllPlaylistsReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetAllPlaylistsReq(bb:flatbuffers.ByteBuffer, obj?:GetAllPlaylistsReq):GetAllPlaylistsReq {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetAllPlaylistsReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

command():COMMAND {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : COMMAND.GET_ALL_PLAYLISTS;
}

static startGetAllPlaylistsReq(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addCommand(builder:flatbuffers.Builder, command:COMMAND) {
  builder.addFieldInt8(0, command, COMMAND.GET_ALL_PLAYLISTS);
}

static endGetAllPlaylistsReq(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetAllPlaylistsReq(builder:flatbuffers.Builder, command:COMMAND):flatbuffers.Offset {
  GetAllPlaylistsReq.startGetAllPlaylistsReq(builder);
  GetAllPlaylistsReq.addCommand(builder, command);
  return GetAllPlaylistsReq.endGetAllPlaylistsReq(builder);
}
}
