// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Playlist } from '../splay-api/playlist.js';


export class GetPlaylistRes {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetPlaylistRes {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetPlaylistRes(bb:flatbuffers.ByteBuffer, obj?:GetPlaylistRes):GetPlaylistRes {
  return (obj || new GetPlaylistRes()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetPlaylistRes(bb:flatbuffers.ByteBuffer, obj?:GetPlaylistRes):GetPlaylistRes {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetPlaylistRes()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

playlist(obj?:Playlist):Playlist|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Playlist()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startGetPlaylistRes(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPlaylist(builder:flatbuffers.Builder, playlistOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, playlistOffset, 0);
}

static endGetPlaylistRes(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetPlaylistRes(builder:flatbuffers.Builder, playlistOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetPlaylistRes.startGetPlaylistRes(builder);
  GetPlaylistRes.addPlaylist(builder, playlistOffset);
  return GetPlaylistRes.endGetPlaylistRes(builder);
}
}
