// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { COMMAND } from '../splay-api/command.js';


export class GetAllCuesReq {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetAllCuesReq {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetAllCuesReq(bb:flatbuffers.ByteBuffer, obj?:GetAllCuesReq):GetAllCuesReq {
  return (obj || new GetAllCuesReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetAllCuesReq(bb:flatbuffers.ByteBuffer, obj?:GetAllCuesReq):GetAllCuesReq {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetAllCuesReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

command():COMMAND {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : COMMAND.GET_ALL_CUES;
}

static startGetAllCuesReq(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addCommand(builder:flatbuffers.Builder, command:COMMAND) {
  builder.addFieldInt8(0, command, COMMAND.GET_ALL_CUES);
}

static endGetAllCuesReq(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetAllCuesReq(builder:flatbuffers.Builder, command:COMMAND):flatbuffers.Offset {
  GetAllCuesReq.startGetAllCuesReq(builder);
  GetAllCuesReq.addCommand(builder, command);
  return GetAllCuesReq.endGetAllCuesReq(builder);
}
}
