// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { CueTable } from '../splay-api/cue-table.js';


export class GetAllCuesRes {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetAllCuesRes {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetAllCuesRes(bb:flatbuffers.ByteBuffer, obj?:GetAllCuesRes):GetAllCuesRes {
  return (obj || new GetAllCuesRes()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetAllCuesRes(bb:flatbuffers.ByteBuffer, obj?:GetAllCuesRes):GetAllCuesRes {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetAllCuesRes()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cues(index: number, obj?:CueTable):CueTable|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CueTable()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

cuesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startGetAllCuesRes(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addCues(builder:flatbuffers.Builder, cuesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cuesOffset, 0);
}

static createCuesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCuesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endGetAllCuesRes(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetAllCuesRes(builder:flatbuffers.Builder, cuesOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetAllCuesRes.startGetAllCuesRes(builder);
  GetAllCuesRes.addCues(builder, cuesOffset);
  return GetAllCuesRes.endGetAllCuesRes(builder);
}
}
