// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { CueTable } from '../splay-api/cue-table.js';


export class GetCueRes {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetCueRes {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetCueRes(bb:flatbuffers.ByteBuffer, obj?:GetCueRes):GetCueRes {
  return (obj || new GetCueRes()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetCueRes(bb:flatbuffers.ByteBuffer, obj?:GetCueRes):GetCueRes {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetCueRes()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cue(obj?:CueTable):CueTable|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CueTable()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startGetCueRes(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addCue(builder:flatbuffers.Builder, cueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cueOffset, 0);
}

static endGetCueRes(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetCueRes(builder:flatbuffers.Builder, cueOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetCueRes.startGetCueRes(builder);
  GetCueRes.addCue(builder, cueOffset);
  return GetCueRes.endGetCueRes(builder);
}
}
