// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { COMMAND } from '../splay-api/command.js';


export class PausePlaylistReq {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PausePlaylistReq {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPausePlaylistReq(bb:flatbuffers.ByteBuffer, obj?:PausePlaylistReq):PausePlaylistReq {
  return (obj || new PausePlaylistReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPausePlaylistReq(bb:flatbuffers.ByteBuffer, obj?:PausePlaylistReq):PausePlaylistReq {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PausePlaylistReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

command():COMMAND {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : COMMAND.PAUSE;
}

playlistId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startPausePlaylistReq(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCommand(builder:flatbuffers.Builder, command:COMMAND) {
  builder.addFieldInt8(0, command, COMMAND.PAUSE);
}

static addPlaylistId(builder:flatbuffers.Builder, playlistId:number) {
  builder.addFieldInt32(1, playlistId, 0);
}

static endPausePlaylistReq(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPausePlaylistReq(builder:flatbuffers.Builder, command:COMMAND, playlistId:number):flatbuffers.Offset {
  PausePlaylistReq.startPausePlaylistReq(builder);
  PausePlaylistReq.addCommand(builder, command);
  PausePlaylistReq.addPlaylistId(builder, playlistId);
  return PausePlaylistReq.endPausePlaylistReq(builder);
}
}
