// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Don't change order
 */
export enum PIXEL_ORDER {
  RGB = 0,
  RBG = 1,
  GRB = 2,
  GBR = 3,
  BRG = 4,
  BGR = 5,
  RGBW = 6,
  RBGW = 7,
  GRBW = 8,
  GBRW = 9,
  BRGW = 10,
  BGRW = 11,
  WRGB = 12,
  WRBG = 13,
  WGRB = 14,
  WGBR = 15,
  WBRG = 16,
  WBGR = 17,
  RWGB = 18,
  RWBG = 19,
  GWRB = 20,
  GWBR = 21,
  BWRG = 22,
  BWGR = 23,
  RGWB = 24,
  RBWG = 25,
  GRWB = 26,
  GBWR = 27,
  BRWG = 28,
  BGWR = 29,
  W = 30,
  RRGGBB = 31,
  RRGGBBWW = 32
}
