// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { COMMAND } from '../splay-api/command.js';


export class PlayPlaylistReq {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlayPlaylistReq {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlayPlaylistReq(bb:flatbuffers.ByteBuffer, obj?:PlayPlaylistReq):PlayPlaylistReq {
  return (obj || new PlayPlaylistReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlayPlaylistReq(bb:flatbuffers.ByteBuffer, obj?:PlayPlaylistReq):PlayPlaylistReq {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlayPlaylistReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

command():COMMAND {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : COMMAND.PLAY;
}

playlistId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startPlayPlaylistReq(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCommand(builder:flatbuffers.Builder, command:COMMAND) {
  builder.addFieldInt8(0, command, COMMAND.PLAY);
}

static addPlaylistId(builder:flatbuffers.Builder, playlistId:number) {
  builder.addFieldInt32(1, playlistId, 0);
}

static endPlayPlaylistReq(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPlayPlaylistReq(builder:flatbuffers.Builder, command:COMMAND, playlistId:number):flatbuffers.Offset {
  PlayPlaylistReq.startPlayPlaylistReq(builder);
  PlayPlaylistReq.addCommand(builder, command);
  PlayPlaylistReq.addPlaylistId(builder, playlistId);
  return PlayPlaylistReq.endPlayPlaylistReq(builder);
}
}
