// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class RecordStop {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RecordStop {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRecordStop(bb:flatbuffers.ByteBuffer, obj?:RecordStop):RecordStop {
  return (obj || new RecordStop()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRecordStop(bb:flatbuffers.ByteBuffer, obj?:RecordStop):RecordStop {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RecordStop()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

time():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startRecordStop(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTime(builder:flatbuffers.Builder, time:number) {
  builder.addFieldInt32(0, time, 0);
}

static endRecordStop(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRecordStop(builder:flatbuffers.Builder, time:number):flatbuffers.Offset {
  RecordStop.startRecordStop(builder);
  RecordStop.addTime(builder, time);
  return RecordStop.endRecordStop(builder);
}
}
