// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class RestorePackage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RestorePackage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRestorePackage(bb:flatbuffers.ByteBuffer, obj?:RestorePackage):RestorePackage {
  return (obj || new RestorePackage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRestorePackage(bb:flatbuffers.ByteBuffer, obj?:RestorePackage):RestorePackage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RestorePackage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

currentSequence():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

lastSequence():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

destination():string|null
destination(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
destination(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

data(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

dataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

dataArray():Int8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Int8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startRestorePackage(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addCurrentSequence(builder:flatbuffers.Builder, currentSequence:number) {
  builder.addFieldInt16(0, currentSequence, 0);
}

static addLastSequence(builder:flatbuffers.Builder, lastSequence:number) {
  builder.addFieldInt16(1, lastSequence, 0);
}

static addDestination(builder:flatbuffers.Builder, destinationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, destinationOffset, 0);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, dataOffset, 0);
}

static createDataVector(builder:flatbuffers.Builder, data:number[]|Int8Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createDataVector(builder:flatbuffers.Builder, data:number[]|Int8Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endRestorePackage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRestorePackage(builder:flatbuffers.Builder, currentSequence:number, lastSequence:number, destinationOffset:flatbuffers.Offset, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  RestorePackage.startRestorePackage(builder);
  RestorePackage.addCurrentSequence(builder, currentSequence);
  RestorePackage.addLastSequence(builder, lastSequence);
  RestorePackage.addDestination(builder, destinationOffset);
  RestorePackage.addData(builder, dataOffset);
  return RestorePackage.endRestorePackage(builder);
}
}
