// automatically generated by the FlatBuffers compiler, do not modify

export enum TRIGGER_TYPE {
  NONE = 0,
  OSC = 1,
  RS232 = 2,
  IO = 3,
  ARTNET = 4,
  DMX = 5,
  SACN = 6,
  POWERUP = 7,
  UDP = 8
}
